import { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Lang = "en" | "fr";

const translations = {
  en: {
    "nav.about": "About",
    "nav.certifications": "Certifications",
    "nav.projects": "Projects",
    "nav.experience": "Intern/Experience",
    "nav.education": "Education",
    "nav.skills": "Skills",
    "nav.motivation": "Motivation",
    "nav.volunteering": "Volunteering",
    "nav.blog": "Blog",
    "toggle.toFrench": "Switch to French",
    "toggle.toEnglish": "Switch to English",

    "hero.subtitle": "Computer Engineering Student",
    "hero.greeting": "Hi, I'm",
    "hero.bio": "Engineering student building",
    "hero.bio.highlight": "LLM-powered security automation",
    "hero.bio.rest": "systems.",
    "hero.stat1": "60% less manual testing",
    "hero.stat2": "85% OWASP detection",
    "hero.stat3": "Top 5% TryHackMe",
    "hero.bio2": "Strong background in AI, DevSecOps, and blockchain-based security architectures.",
    "hero.downloadCv": "Download CV",
    "hero.contact": "Contact Me",
    "hero.skillsMatrix": "Skills Matrix",
    "hero.askAi": "Ask AI",
    "hero.activity": "Activity",
    "hero.chatbot": "Portfolio AI Assistant",
    "hero.backToPortfolio": "Back to Portfolio",
    "hero.contactForm": "Contact Me",
    "hero.contactName": "Your Name",
    "hero.contactEmail": "Your Email",
    "hero.contactMessage": "Your Message",
    "hero.contactSend": "Send Message",
    "hero.contactSuccess": "Message sent successfully!",
    "hero.contactError": "Failed to send message, please try again.",
    "hero.stats.projectsCompleted": "Projects Completed",
    "hero.stats.experience": "Intern/Experience",
    "hero.stats.certifications": "Certifications",
    "hero.loading.line1": "Initializing system...",
    "hero.loading.line2": "Loading security modules...",
    "hero.loading.line3": "Connecting to portfolio...",
    "hero.loading.line4": "Access granted.",
    "hero.loading.systemLabel": "Portfolio System",

    "skills.title": "Skills & Tools",
    "skills.subtitle": "Technologies and methodologies I utilize for secure development and analysis",
    "skills.label": "Technical Skills",
    "skills.category.languages": "Languages",
    "skills.category.frameworks": "Frameworks",
    "skills.category.securityTools": "Security Tools",
    "skills.category.devops": "DevOps & Tools",

    "certifications.title": "Certifications",
    "certifications.eyebrow": "Professional Credentials",
    "certifications.subtitle": "Industry-recognized certifications demonstrating expertise in cybersecurity, AI, and cloud technologies",
    "certifications.tab.all": "All",
    "certifications.tab.dev": "Dev",
    "certifications.tab.ai": "AI",
    "certifications.tab.cybersecurity": "Cybersecurity",
    "certifications.details": "Details",
    "certifications.verify": "Verify",

    "projects.title": "Projects",
    "projects.eyebrow": "Portfolio",
    "projects.featured": "Featured Projects",
    "projects.subtitle": "Showcasing real-world cybersecurity projects and solutions I've developed",
    "projects.tab.all": "All",
    "projects.tab.cybersecurity": "Cybersecurity",
    "projects.tab.ai": "AI",
    "projects.tab.dev": "Dev",
    "projects.source": "View Source Code",
    "projects.highlights": "Key Highlights:",
    "projects.more": "more (click to view)",
    "projects.technologies": "Technologies:",
    "projects.about": "About the Project",
    "projects.modal.highlights": "Key Highlights",
    "projects.modal.technologies": "Technologies",

    "education.title": "Education",
    "education.eyebrow": "Academic Background",
    "education.subtitle": "Continuous learning and academic excellence in cybersecurity and computer science",
    "education.coursework": "Key Coursework:",
    "education.achievements": "Achievements:",
    "education.continuing": "Continuing Education",

    "motivation.title": "Motivation",
    "motivation.eyebrow": "What Drives Me",
    "motivation.subtitle": "The passion and principles that guide my cybersecurity journey",
    "motivation.story.title": "My Journey Into Cybersecurity",
    "motivation.story.p1": "My fascination with cybersecurity began during my computer science studies when I first learned about buffer overflow attacks. The idea that a simple programming mistake could lead to system compromise was both terrifying and fascinating.",
    "motivation.story.p2": "This curiosity led me to participate in my first Capture The Flag competition, where I experienced the thrill of ethical hacking and the satisfaction of finding and fixing vulnerabilities. The collaborative nature of the cybersecurity community convinced me this was the field where I belonged.",
    "motivation.story.p3": "Today, every project I work on and every vulnerability I discover reinforces my belief that cybersecurity is not just a career - it is a calling to protect and serve the digital world we all depend on.",
    "motivation.section.motivates": "What Motivates Me",
    "motivation.section.values": "Core Values",
    "motivation.quote": "\"Security is not a product, but a process. It's not about perfection, but about continuous improvement and adaptation to new challenges.\"",
    "motivation.quote.author": "- My Personal Philosophy",
    "motivation.m1.title": "Protecting Digital Lives",
    "motivation.m1.desc": "Every day, millions of people rely on digital systems for their personal and professional lives. I'm motivated by the opportunity to protect these systems and the people who depend on them from cyber threats.",
    "motivation.m2.title": "Solving Complex Puzzles",
    "motivation.m2.desc": "Cybersecurity is like solving an ever-evolving puzzle. Each new vulnerability, attack vector, or security challenge requires creative thinking and technical expertise.",
    "motivation.m3.title": "Global Impact",
    "motivation.m3.desc": "Cyber threats know no borders. Working in cybersecurity means contributing to global digital safety and helping build a more secure internet for everyone.",
    "motivation.m4.title": "Community & Mentorship",
    "motivation.m4.desc": "The cybersecurity community is collaborative. I'm passionate about sharing knowledge, mentoring newcomers, and building stronger security teams.",
    "motivation.v1.title": "Continuous Learning",
    "motivation.v1.desc": "Technology evolves rapidly, and so do threats. I'm committed to staying current with modern security tools, trends, and techniques.",
    "motivation.v2.title": "Ethical Foundation",
    "motivation.v2.desc": "Using my skills responsibly and ethically is essential. I believe in defensive security, responsible disclosure, and protective hacking.",
    "motivation.v3.title": "Innovation & Automation",
    "motivation.v3.desc": "I'm driven to automate security processes, develop innovative tools, and improve efficiency in security operations.",
    "motivation.v4.title": "Knowledge Sharing",
    "motivation.v4.desc": "Security gets stronger when knowledge is shared. I enjoy documenting findings, teaching others, and contributing to the cybersecurity community.",

    "experience.title": "Intern/Experience",
    "internships.overview": "Overview",
    "internships.technologies": "Technologies & Skills",
    "internships.visitCompany": "Visit Company",
    "internships.viewCertificate": "View Certificate",

    "activity.eyebrow": "Open Source & Security",
    "activity.title": "Activity & Achievements",
    "activity.subtitle": "Tracking my contributions to open source and progress in cybersecurity training.",
    "activity.tryhackmeProgress": "TryHackMe Progress",

    "github.contributions": "GitHub Contributions",
    "github.contributions.lastYear": "contributions in the last year",
    "github.rank": "Tunisia Rank",
    "github.calendar.loading": "Loading contributions...",
    "github.calendar.error": "Unable to load GitHub activity",
    "github.calendar.less": "Less",
    "github.calendar.more": "More",
    "github.achievement.title": "GitHub Achievements",
    "github.achievement.subtitle": "Badges earned from GitHub activity",
    "github.achievement.error": "Error loading achievements",
    "github.achievement.hint": "Make sure the backend server is running (npm run dev).",

    "tryhackme.profile": "TryHackMe Profile",
    "tryhackme.subtitle": "Cybersecurity Training Progress",
    "tryhackme.level": "Level",
    "tryhackme.globalRank": "Global Rank",
    "tryhackme.percentile": "Percentile",
    "tryhackme.roomsCompleted": "Rooms Completed",
    "tryhackme.badgesEarned": "Badges Earned",
    "tryhackme.error": "Error loading TryHackMe stats",

    "cv.previewTitle": "CV Preview",

    "footer.bio": "Engineering student building LLM-powered security automation systems.",
    "footer.backToTop": "Back to top",
    "footer.rights": "All rights reserved.",
    "footer.builtWith": "Built with React, TypeScript & Tailwind CSS",

    "hire.status": "Open to opportunities",
    "hire.detail": "- Available for internships & collaborations",
    "hire.vcard": "vCard",
    "hire.cta": "Hire Me",

    "blog.title": "Blog & Write-ups",
    "blog.subtitle": "CTF write-ups, security research, and AI tutorials",
    "blog.back": "Back to Portfolio",
    "blog.readMore": "Read more",
    "blog.comingSoon": "More articles coming soon...",
    "blog.heading.left": "Blog",
    "blog.heading.right": "Write-ups",
    "blog.category.ctf": "CTF",
    "blog.category.security": "Security",
    "blog.category.ai": "AI",
    "blog.category.tutorial": "Tutorial",

    "achievements.title": "Achievements at a Glance",
    "achievements.ieeeRoles": "IEEE Roles",
    "achievements.certifications": "Certifications",
    "achievements.projects": "Projects",
    "achievements.internships": "Internships",
    "achievements.volunteering": "Volunteering",
    "achievements.degrees": "Degrees",

    "volunteering.back": "Back to Portfolio",
    "volunteering.navTitle": "Volunteering & Leadership",
    "volunteering.title.left": "Volunteering",
    "volunteering.title.right": "Leadership",
    "volunteering.subtitle": "Community engagement, professional leadership, and civic involvement",
    "volunteering.roles": "roles",
    "volunteering.legend.ieee": "IEEE",
    "volunteering.legend.community": "Community",
    "volunteering.legend.jci": "JCI",
    "volunteering.legend.association": "Associations",
    "volunteering.badge.leadership": "Leadership",
    "volunteering.badge.officer": "Officer",
    "volunteering.badge.civic": "Civic",

    "404.title": "ACCESS DENIED",
    "404.subtitle": "The page you're looking for doesn't exist or has been moved.",
    "404.home": "Return to Base",

    "cv.title": "Curriculum Vitae",
    "cv.english": "English Version",
    "cv.french": "French Version",
    "cv.preview": "Preview",
    "cv.download": "Download",

    "details.noImage": "No certificate image available",
    "details.issued": "Issued:",
    "details.description": "Description",
    "details.skillsVerified": "Skills Verified",
    "details.viewOfficial": "View Official Credential",

    "chat.greeting": "Hello! I'm Malek's AI assistant. I can tell you about his projects, internships, certifications, and skills. What would you like to know?",
    "chat.input": "Ask about my projects, skills...",
    "chat.send": "Send",
    "chat.error": "Sorry, I encountered an error. Please try again.",
  },
  fr: {
    "nav.about": "A propos",
    "nav.certifications": "Certifications",
    "nav.projects": "Projets",
    "nav.experience": "Stages/Experience",
    "nav.education": "Formation",
    "nav.skills": "Competences",
    "nav.motivation": "Motivation",
    "nav.volunteering": "Benevolat",
    "nav.blog": "Blog",
    "toggle.toFrench": "Passer en francais",
    "toggle.toEnglish": "Switch to English",

    "hero.subtitle": "Etudiant en genie informatique",
    "hero.greeting": "Bonjour, je suis",
    "hero.bio": "Etudiant en ingenierie developpant des",
    "hero.bio.highlight": "systemes d'automatisation de securite bases sur les LLM",
    "hero.bio.rest": ".",
    "hero.stat1": "60% moins de tests manuels",
    "hero.stat2": "85% de detection OWASP",
    "hero.stat3": "Top 5% TryHackMe",
    "hero.bio2": "Solide experience en IA, DevSecOps et architectures de securite basees sur la blockchain.",
    "hero.downloadCv": "Telecharger le CV",
    "hero.contact": "Me Contacter",
    "hero.skillsMatrix": "Matrice de competences",
    "hero.askAi": "Demander IA",
    "hero.activity": "Activite",
    "hero.chatbot": "Assistant IA du Portfolio",
    "hero.backToPortfolio": "Retour au Portfolio",
    "hero.contactForm": "Me Contacter",
    "hero.contactName": "Votre nom",
    "hero.contactEmail": "Votre email",
    "hero.contactMessage": "Votre message",
    "hero.contactSend": "Envoyer le message",
    "hero.contactSuccess": "Message envoye avec succes !",
    "hero.contactError": "Echec de l'envoi du message, veuillez reessayer.",
    "hero.stats.projectsCompleted": "Projets termines",
    "hero.stats.experience": "Stages/Experience",
    "hero.stats.certifications": "Certifications",
    "hero.loading.line1": "Initialisation du systeme...",
    "hero.loading.line2": "Chargement des modules de securite...",
    "hero.loading.line3": "Connexion au portfolio...",
    "hero.loading.line4": "Acces autorise.",
    "hero.loading.systemLabel": "Systeme Portfolio",

    "skills.title": "Competences & Outils",
    "skills.subtitle": "Technologies et methodologies que j'utilise pour le developpement securise et l'analyse",
    "skills.label": "Competences Techniques",
    "skills.category.languages": "Langages",
    "skills.category.frameworks": "Frameworks",
    "skills.category.securityTools": "Outils de securite",
    "skills.category.devops": "DevOps & Outils",

    "certifications.title": "Certifications",
    "certifications.eyebrow": "References professionnelles",
    "certifications.subtitle": "Certifications reconnues qui prouvent mon expertise en cybersecurite, IA et cloud",
    "certifications.tab.all": "Tous",
    "certifications.tab.dev": "Dev",
    "certifications.tab.ai": "IA",
    "certifications.tab.cybersecurity": "Cybersecurite",
    "certifications.details": "Details",
    "certifications.verify": "Verifier",

    "projects.title": "Projets",
    "projects.eyebrow": "Portfolio",
    "projects.featured": "Projets phares",
    "projects.subtitle": "Presentation de projets et solutions de cybersecurite developpes en conditions reelles",
    "projects.tab.all": "Tous",
    "projects.tab.cybersecurity": "Cybersecurite",
    "projects.tab.ai": "IA",
    "projects.tab.dev": "Dev",
    "projects.source": "Voir le code source",
    "projects.highlights": "Points cles :",
    "projects.more": "de plus (cliquer pour voir)",
    "projects.technologies": "Technologies :",
    "projects.about": "A propos du projet",
    "projects.modal.highlights": "Points cles",
    "projects.modal.technologies": "Technologies",

    "education.title": "Formation",
    "education.eyebrow": "Parcours academique",
    "education.subtitle": "Apprentissage continu et excellence academique en cybersecurite et informatique",
    "education.coursework": "Cours principaux :",
    "education.achievements": "Realisations :",
    "education.continuing": "Formation continue",

    "motivation.title": "Motivation",
    "motivation.eyebrow": "Ce qui me motive",
    "motivation.subtitle": "La passion et les principes qui guident mon parcours en cybersecurite",
    "motivation.story.title": "Mon parcours vers la cybersecurite",
    "motivation.story.p1": "Ma fascination pour la cybersecurite a commence pendant mes etudes en informatique lorsque j'ai decouvert les attaques de type buffer overflow. L'idee qu'une simple erreur de code puisse compromettre un systeme etait a la fois inquietante et fascinante.",
    "motivation.story.p2": "Cette curiosite m'a pousse a participer a mon premier CTF, ou j'ai ressenti le frisson du hacking ethique et la satisfaction de trouver puis corriger des vulnerabilites. La collaboration dans la communaute cybersecurite m'a convaincu que c'etait mon domaine.",
    "motivation.story.p3": "Aujourd'hui, chaque projet et chaque faille identifiee renforcent ma conviction que la cybersecurite n'est pas seulement un metier - c'est une mission pour proteger le monde numerique dont nous dependons tous.",
    "motivation.section.motivates": "Ce qui me motive",
    "motivation.section.values": "Valeurs fondamentales",
    "motivation.quote": "\"La securite n'est pas un produit, c'est un processus. Ce n'est pas la perfection qui compte, mais l'amelioration continue et l'adaptation.\"",
    "motivation.quote.author": "- Ma philosophie personnelle",
    "motivation.m1.title": "Proteger les vies numeriques",
    "motivation.m1.desc": "Chaque jour, des millions de personnes dependent de systemes numeriques. Je suis motive par l'opportunite de proteger ces systemes et les personnes qui en dependent.",
    "motivation.m2.title": "Resoudre des problemes complexes",
    "motivation.m2.desc": "La cybersecurite ressemble a un puzzle en evolution permanente. Chaque nouvelle faille ou vecteur d'attaque demande creativite et expertise technique.",
    "motivation.m3.title": "Impact global",
    "motivation.m3.desc": "Les menaces cyber n'ont pas de frontieres. Travailler en cybersecurite, c'est contribuer a la securite numerique mondiale.",
    "motivation.m4.title": "Communaute & mentorat",
    "motivation.m4.desc": "La communaute cybersecurite est collaborative. J'aime partager les connaissances, accompagner les debutants et renforcer les equipes.",
    "motivation.v1.title": "Apprentissage continu",
    "motivation.v1.desc": "La technologie evolue vite, les menaces aussi. Je m'engage a rester a jour sur les outils et techniques modernes.",
    "motivation.v2.title": "Fondation ethique",
    "motivation.v2.desc": "Utiliser mes competences de maniere responsable est essentiel. Je crois en la securite defensive et la divulgation responsable.",
    "motivation.v3.title": "Innovation & automatisation",
    "motivation.v3.desc": "Je cherche a automatiser les processus de securite, creer des outils innovants et gagner en efficacite.",
    "motivation.v4.title": "Partage de connaissances",
    "motivation.v4.desc": "La securite devient plus forte quand la connaissance est partagee. J'aime documenter, enseigner et contribuer.",

    "experience.title": "Stages/Experience",
    "internships.overview": "Apercu",
    "internships.technologies": "Technologies & competences",
    "internships.visitCompany": "Visiter l'entreprise",
    "internships.viewCertificate": "Voir le certificat",

    "activity.eyebrow": "Open Source & Securite",
    "activity.title": "Activite & Realisations",
    "activity.subtitle": "Suivi de mes contributions open source et de mes progres en formation cybersecurite.",
    "activity.tryhackmeProgress": "Progression TryHackMe",

    "github.contributions": "Contributions GitHub",
    "github.contributions.lastYear": "contributions durant la derniere annee",
    "github.rank": "Classement Tunisie",
    "github.calendar.loading": "Chargement des contributions...",
    "github.calendar.error": "Impossible de charger l'activite GitHub",
    "github.calendar.less": "Moins",
    "github.calendar.more": "Plus",
    "github.achievement.title": "Realisations GitHub",
    "github.achievement.subtitle": "Badges obtenus via l'activite GitHub",
    "github.achievement.error": "Erreur lors du chargement des realisations",
    "github.achievement.hint": "Verifiez que le serveur backend est actif (npm run dev).",

    "tryhackme.profile": "Profil TryHackMe",
    "tryhackme.subtitle": "Progression en formation cybersecurite",
    "tryhackme.level": "Niveau",
    "tryhackme.globalRank": "Classement mondial",
    "tryhackme.percentile": "Percentile",
    "tryhackme.roomsCompleted": "Rooms completees",
    "tryhackme.badgesEarned": "Badges obtenus",
    "tryhackme.error": "Erreur lors du chargement des stats TryHackMe",

    "cv.previewTitle": "Apercu du CV",

    "footer.bio": "Etudiant en ingenierie developpant des systemes d'automatisation de securite bases sur les LLM.",
    "footer.backToTop": "Retour en haut",
    "footer.rights": "Tous droits reserves.",
    "footer.builtWith": "Construit avec React, TypeScript & Tailwind CSS",

    "hire.status": "Ouvert aux opportunites",
    "hire.detail": "- Disponible pour stages et collaborations",
    "hire.vcard": "vCard",
    "hire.cta": "Recrutez-moi",

    "blog.title": "Blog & Articles",
    "blog.subtitle": "Write-ups CTF, recherche en securite et tutoriels IA",
    "blog.back": "Retour au Portfolio",
    "blog.readMore": "Lire plus",
    "blog.comingSoon": "Plus d'articles a venir...",
    "blog.heading.left": "Blog",
    "blog.heading.right": "Write-ups",
    "blog.category.ctf": "CTF",
    "blog.category.security": "Securite",
    "blog.category.ai": "IA",
    "blog.category.tutorial": "Tutoriel",

    "achievements.title": "Realisations en un coup d'oeil",
    "achievements.ieeeRoles": "Roles IEEE",
    "achievements.certifications": "Certifications",
    "achievements.projects": "Projets",
    "achievements.internships": "Stages",
    "achievements.volunteering": "Benevolat",
    "achievements.degrees": "Diplomes",

    "volunteering.back": "Retour au Portfolio",
    "volunteering.navTitle": "Benevolat & Leadership",
    "volunteering.title.left": "Benevolat",
    "volunteering.title.right": "Leadership",
    "volunteering.subtitle": "Engagement communautaire, leadership professionnel et implication citoyenne",
    "volunteering.roles": "roles",
    "volunteering.legend.ieee": "IEEE",
    "volunteering.legend.community": "Communaute",
    "volunteering.legend.jci": "JCI",
    "volunteering.legend.association": "Associations",
    "volunteering.badge.leadership": "Leadership",
    "volunteering.badge.officer": "Responsable",
    "volunteering.badge.civic": "Civique",

    "404.title": "ACCES REFUSE",
    "404.subtitle": "La page que vous cherchez n'existe pas ou a ete deplacee.",
    "404.home": "Retour a l'accueil",

    "cv.title": "Curriculum Vitae",
    "cv.english": "Version anglaise",
    "cv.french": "Version francaise",
    "cv.preview": "Apercu",
    "cv.download": "Telecharger",

    "details.noImage": "Aucune image de certificat disponible",
    "details.issued": "Delivre le :",
    "details.description": "Description",
    "details.skillsVerified": "Competences verifiees",
    "details.viewOfficial": "Voir l'attestation officielle",

    "chat.greeting": "Bonjour ! Je suis l'assistant IA de Malek. Je peux vous parler de ses projets, stages, certifications et competences. Que voulez-vous savoir ?",
    "chat.input": "Demandez-moi ses projets, competences...",
    "chat.send": "Envoyer",
    "chat.error": "Desole, une erreur est survenue. Veuillez reessayer.",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("portfolio-lang");
    return (saved === "fr" ? "fr" : "en") as Lang;
  });

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const handleSetLang = (newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("portfolio-lang", newLang);
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
