import { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Lang = "en" | "fr" | "ar";

const translations = {
  en: {
    "nav.about": "About",
    "nav.certifications": "Certifications",
    "nav.projects": "Projects",
    "nav.experience": "Intern/Experience",
    "nav.education": "Education",
    "nav.skills": "Skills",
    "nav.motivation": "Motivation",
    "nav.volunteering": "Volunteering",
    "nav.blog": "Blog",
    "toggle.toFrench": "Switch to French",
    "toggle.toEnglish": "Switch to English",

    "hero.subtitle": "Computer Engineering Student",
    "hero.greeting": "Hi, I'm",
    "hero.bio": "Engineering student building",
    "hero.bio.highlight": "LLM-powered security automation",
    "hero.bio.rest": "systems.",
    "hero.stat1": "60% less manual testing",
    "hero.stat2": "85% OWASP detection",
    "hero.stat3": "Top 5% TryHackMe",
    "hero.bio2": "Strong background in AI, DevSecOps, and blockchain-based security architectures.",
    "hero.downloadCv": "Download CV",
    "hero.contact": "Contact Me",
    "hero.skillsMatrix": "Skills Matrix",
    "hero.askAi": "Ask AI",
    "hero.activity": "Activity",
    "hero.chatbot": "Portfolio AI Assistant",
    "hero.backToPortfolio": "Back to Portfolio",
    "hero.contactForm": "Contact Me",
    "hero.contactName": "Your Name",
    "hero.contactEmail": "Your Email",
    "hero.contactMessage": "Your Message",
    "hero.contactSend": "Send Message",
    "hero.contactSuccess": "Message sent successfully!",
    "hero.contactError": "Failed to send message, please try again.",
    "hero.stats.projectsCompleted": "Projects Completed",
    "hero.stats.experience": "Intern/Experience",
    "hero.stats.certifications": "Certifications",
    "hero.loading.line1": "Initializing system...",
    "hero.loading.line2": "Loading security modules...",
    "hero.loading.line3": "Connecting to portfolio...",
    "hero.loading.line4": "Access granted.",
    "hero.loading.systemLabel": "Portfolio System",

    "skills.title": "Skills & Tools",
    "skills.subtitle": "Technologies and methodologies I utilize for secure development and analysis",
    "skills.label": "Technical Skills",
    "skills.category.languages": "Languages",
    "skills.category.frameworks": "Frameworks",
    "skills.category.securityTools": "Security Tools",
    "skills.category.devops": "DevOps & Tools",

    "certifications.title": "Certifications",
    "certifications.eyebrow": "Professional Credentials",
    "certifications.subtitle": "Industry-recognized certifications demonstrating expertise in cybersecurity, AI, and cloud technologies",
    "certifications.tab.all": "All",
    "certifications.tab.dev": "Dev",
    "certifications.tab.ai": "AI",
    "certifications.tab.cybersecurity": "Cybersecurity",
    "certifications.details": "Details",
    "certifications.verify": "Verify",

    "projects.title": "Projects",
    "projects.eyebrow": "Portfolio",
    "projects.featured": "Featured Projects",
    "projects.subtitle": "Showcasing real-world cybersecurity projects and solutions I've developed",
    "projects.tab.all": "All",
    "projects.tab.cybersecurity": "Cybersecurity",
    "projects.tab.ai": "AI",
    "projects.tab.dev": "Dev",
    "projects.source": "View Source Code",
    "projects.highlights": "Key Highlights:",
    "projects.more": "more (click to view)",
    "projects.technologies": "Technologies:",
    "projects.about": "About the Project",
    "projects.modal.highlights": "Key Highlights",
    "projects.modal.technologies": "Technologies",

    "education.title": "Education",
    "education.eyebrow": "Academic Background",
    "education.subtitle": "Continuous learning and academic excellence in cybersecurity and computer science",
    "education.coursework": "Key Coursework:",
    "education.achievements": "Achievements:",
    "education.continuing": "Continuing Education",

    "motivation.title": "Motivation",
    "motivation.eyebrow": "What Drives Me",
    "motivation.subtitle": "The passion and principles that guide my cybersecurity journey",
    "motivation.story.title": "My Journey Into Cybersecurity",
    "motivation.story.p1": "My fascination with cybersecurity began during my computer science studies when I first learned about buffer overflow attacks. The idea that a simple programming mistake could lead to system compromise was both terrifying and fascinating.",
    "motivation.story.p2": "This curiosity led me to participate in my first Capture The Flag competition, where I experienced the thrill of ethical hacking and the satisfaction of finding and fixing vulnerabilities. The collaborative nature of the cybersecurity community convinced me this was the field where I belonged.",
    "motivation.story.p3": "Today, every project I work on and every vulnerability I discover reinforces my belief that cybersecurity is not just a career - it is a calling to protect and serve the digital world we all depend on.",
    "motivation.section.motivates": "What Motivates Me",
    "motivation.section.values": "Core Values",
    "motivation.quote": "\"Security is not a product, but a process. It's not about perfection, but about continuous improvement and adaptation to new challenges.\"",
    "motivation.quote.author": "- My Personal Philosophy",
    "motivation.m1.title": "Protecting Digital Lives",
    "motivation.m1.desc": "Every day, millions of people rely on digital systems for their personal and professional lives. I'm motivated by the opportunity to protect these systems and the people who depend on them from cyber threats.",
    "motivation.m2.title": "Solving Complex Puzzles",
    "motivation.m2.desc": "Cybersecurity is like solving an ever-evolving puzzle. Each new vulnerability, attack vector, or security challenge requires creative thinking and technical expertise.",
    "motivation.m3.title": "Global Impact",
    "motivation.m3.desc": "Cyber threats know no borders. Working in cybersecurity means contributing to global digital safety and helping build a more secure internet for everyone.",
    "motivation.m4.title": "Community & Mentorship",
    "motivation.m4.desc": "The cybersecurity community is collaborative. I'm passionate about sharing knowledge, mentoring newcomers, and building stronger security teams.",
    "motivation.v1.title": "Continuous Learning",
    "motivation.v1.desc": "Technology evolves rapidly, and so do threats. I'm committed to staying current with modern security tools, trends, and techniques.",
    "motivation.v2.title": "Ethical Foundation",
    "motivation.v2.desc": "Using my skills responsibly and ethically is essential. I believe in defensive security, responsible disclosure, and protective hacking.",
    "motivation.v3.title": "Innovation & Automation",
    "motivation.v3.desc": "I'm driven to automate security processes, develop innovative tools, and improve efficiency in security operations.",
    "motivation.v4.title": "Knowledge Sharing",
    "motivation.v4.desc": "Security gets stronger when knowledge is shared. I enjoy documenting findings, teaching others, and contributing to the cybersecurity community.",

    "experience.title": "Intern/Experience",
    "internships.overview": "Overview",
    "internships.technologies": "Technologies & Skills",
    "internships.visitCompany": "Visit Company",
    "internships.viewCertificate": "View Certificate",

    "activity.eyebrow": "Open Source & Security",
    "activity.title": "Activity & Achievements",
    "activity.subtitle": "Tracking my contributions to open source and progress in cybersecurity training.",
    "activity.tryhackmeProgress": "TryHackMe Progress",

    "github.contributions": "GitHub Contributions",
    "github.contributions.lastYear": "contributions in the last year",
    "github.rank": "Tunisia Rank",
    "github.calendar.loading": "Loading contributions...",
    "github.calendar.error": "Unable to load GitHub activity",
    "github.calendar.less": "Less",
    "github.calendar.more": "More",
    "github.achievement.title": "GitHub Achievements",
    "github.achievement.subtitle": "Badges earned from GitHub activity",
    "github.achievement.error": "Error loading achievements",
    "github.achievement.hint": "Make sure the backend server is running (npm run dev).",

    "tryhackme.profile": "TryHackMe Profile",
    "tryhackme.subtitle": "Cybersecurity Training Progress",
    "tryhackme.level": "Level",
    "tryhackme.globalRank": "Global Rank",
    "tryhackme.percentile": "Percentile",
    "tryhackme.roomsCompleted": "Rooms Completed",
    "tryhackme.badgesEarned": "Badges Earned",
    "tryhackme.error": "Error loading TryHackMe stats",

    "cv.previewTitle": "CV Preview",

    "footer.bio": "Engineering student building LLM-powered security automation systems.",
    "footer.backToTop": "Back to top",
    "footer.rights": "All rights reserved.",
    "footer.builtWith": "Built with React, TypeScript & Tailwind CSS",

    "hire.status": "Open to opportunities",
    "hire.detail": "- Available for internships & collaborations",
    "hire.vcard": "vCard",
    "hire.cta": "Hire Me",

    "blog.title": "Blog & Write-ups",
    "blog.subtitle": "CTF write-ups, security research, and AI tutorials",
    "blog.back": "Back to Portfolio",
    "blog.readMore": "Read more",
    "blog.comingSoon": "More articles coming soon...",
    "blog.heading.left": "Blog",
    "blog.heading.right": "Write-ups",
    "blog.category.ctf": "CTF",
    "blog.category.security": "Security",
    "blog.category.ai": "AI",
    "blog.category.tutorial": "Tutorial",

    "achievements.title": "Achievements at a Glance",
    "achievements.ieeeRoles": "IEEE Roles",
    "achievements.certifications": "Certifications",
    "achievements.projects": "Projects",
    "achievements.internships": "Internships",
    "achievements.volunteering": "Volunteering",
    "achievements.degrees": "Degrees",

    "volunteering.back": "Back to Portfolio",
    "volunteering.navTitle": "Volunteering & Leadership",
    "volunteering.title.left": "Volunteering",
    "volunteering.title.right": "Leadership",
    "volunteering.subtitle": "Community engagement, professional leadership, and civic involvement",
    "volunteering.roles": "roles",
    "volunteering.legend.ieee": "IEEE",
    "volunteering.legend.community": "Community",
    "volunteering.legend.jci": "JCI",
    "volunteering.legend.association": "Associations",
    "volunteering.badge.leadership": "Leadership",
    "volunteering.badge.officer": "Officer",
    "volunteering.badge.civic": "Civic",

    "404.title": "ACCESS DENIED",
    "404.subtitle": "The page you're looking for doesn't exist or has been moved.",
    "404.home": "Return to Base",

    "cv.title": "Curriculum Vitae",
    "cv.english": "English Version",
    "cv.french": "French Version",
    "cv.preview": "Preview",
    "cv.download": "Download",

    "details.noImage": "No certificate image available",
    "details.issued": "Issued:",
    "details.description": "Description",
    "details.skillsVerified": "Skills Verified",
    "details.viewOfficial": "View Official Credential",

    "chat.greeting": "Hello! I'm Malek's AI assistant. I can tell you about his projects, internships, certifications, and skills. What would you like to know?",
    "chat.input": "Ask about my projects, skills...",
    "chat.send": "Send",
    "chat.error": "Sorry, I encountered an error. Please try again.",

    "welcome.title": "Welcome",
    "welcome.subtitle": "How would you like to explore my portfolio?",
    "welcome.technical": "I'm Technical",
    "welcome.technicalDesc": "Full portfolio with projects, skills, blog & more",
    "welcome.recruiter": "I'm a Recruiter",
    "welcome.recruiterDesc": "One-page summary optimized for hiring decisions",
  },
  fr: {
    "nav.about": "A propos",
    "nav.certifications": "Certifications",
    "nav.projects": "Projets",
    "nav.experience": "Stages/Experience",
    "nav.education": "Formation",
    "nav.skills": "Competences",
    "nav.motivation": "Motivation",
    "nav.volunteering": "Benevolat",
    "nav.blog": "Blog",
    "toggle.toFrench": "Passer en francais",
    "toggle.toEnglish": "Switch to English",

    "hero.subtitle": "Etudiant en genie informatique",
    "hero.greeting": "Bonjour, je suis",
    "hero.bio": "Etudiant en ingenierie developpant des",
    "hero.bio.highlight": "systemes d'automatisation de securite bases sur les LLM",
    "hero.bio.rest": ".",
    "hero.stat1": "60% moins de tests manuels",
    "hero.stat2": "85% de detection OWASP",
    "hero.stat3": "Top 5% TryHackMe",
    "hero.bio2": "Solide experience en IA, DevSecOps et architectures de securite basees sur la blockchain.",
    "hero.downloadCv": "Telecharger le CV",
    "hero.contact": "Me Contacter",
    "hero.skillsMatrix": "Matrice de competences",
    "hero.askAi": "Demander IA",
    "hero.activity": "Activite",
    "hero.chatbot": "Assistant IA du Portfolio",
    "hero.backToPortfolio": "Retour au Portfolio",
    "hero.contactForm": "Me Contacter",
    "hero.contactName": "Votre nom",
    "hero.contactEmail": "Votre email",
    "hero.contactMessage": "Votre message",
    "hero.contactSend": "Envoyer le message",
    "hero.contactSuccess": "Message envoye avec succes !",
    "hero.contactError": "Echec de l'envoi du message, veuillez reessayer.",
    "hero.stats.projectsCompleted": "Projets termines",
    "hero.stats.experience": "Stages/Experience",
    "hero.stats.certifications": "Certifications",
    "hero.loading.line1": "Initialisation du systeme...",
    "hero.loading.line2": "Chargement des modules de securite...",
    "hero.loading.line3": "Connexion au portfolio...",
    "hero.loading.line4": "Acces autorise.",
    "hero.loading.systemLabel": "Systeme Portfolio",

    "skills.title": "Competences & Outils",
    "skills.subtitle": "Technologies et methodologies que j'utilise pour le developpement securise et l'analyse",
    "skills.label": "Competences Techniques",
    "skills.category.languages": "Langages",
    "skills.category.frameworks": "Frameworks",
    "skills.category.securityTools": "Outils de securite",
    "skills.category.devops": "DevOps & Outils",

    "certifications.title": "Certifications",
    "certifications.eyebrow": "References professionnelles",
    "certifications.subtitle": "Certifications reconnues qui prouvent mon expertise en cybersecurite, IA et cloud",
    "certifications.tab.all": "Tous",
    "certifications.tab.dev": "Dev",
    "certifications.tab.ai": "IA",
    "certifications.tab.cybersecurity": "Cybersecurite",
    "certifications.details": "Details",
    "certifications.verify": "Verifier",

    "projects.title": "Projets",
    "projects.eyebrow": "Portfolio",
    "projects.featured": "Projets phares",
    "projects.subtitle": "Presentation de projets et solutions de cybersecurite developpes en conditions reelles",
    "projects.tab.all": "Tous",
    "projects.tab.cybersecurity": "Cybersecurite",
    "projects.tab.ai": "IA",
    "projects.tab.dev": "Dev",
    "projects.source": "Voir le code source",
    "projects.highlights": "Points cles :",
    "projects.more": "de plus (cliquer pour voir)",
    "projects.technologies": "Technologies :",
    "projects.about": "A propos du projet",
    "projects.modal.highlights": "Points cles",
    "projects.modal.technologies": "Technologies",

    "education.title": "Formation",
    "education.eyebrow": "Parcours academique",
    "education.subtitle": "Apprentissage continu et excellence academique en cybersecurite et informatique",
    "education.coursework": "Cours principaux :",
    "education.achievements": "Realisations :",
    "education.continuing": "Formation continue",

    "motivation.title": "Motivation",
    "motivation.eyebrow": "Ce qui me motive",
    "motivation.subtitle": "La passion et les principes qui guident mon parcours en cybersecurite",
    "motivation.story.title": "Mon parcours vers la cybersecurite",
    "motivation.story.p1": "Ma fascination pour la cybersecurite a commence pendant mes etudes en informatique lorsque j'ai decouvert les attaques de type buffer overflow. L'idee qu'une simple erreur de code puisse compromettre un systeme etait a la fois inquietante et fascinante.",
    "motivation.story.p2": "Cette curiosite m'a pousse a participer a mon premier CTF, ou j'ai ressenti le frisson du hacking ethique et la satisfaction de trouver puis corriger des vulnerabilites. La collaboration dans la communaute cybersecurite m'a convaincu que c'etait mon domaine.",
    "motivation.story.p3": "Aujourd'hui, chaque projet et chaque faille identifiee renforcent ma conviction que la cybersecurite n'est pas seulement un metier - c'est une mission pour proteger le monde numerique dont nous dependons tous.",
    "motivation.section.motivates": "Ce qui me motive",
    "motivation.section.values": "Valeurs fondamentales",
    "motivation.quote": "\"La securite n'est pas un produit, c'est un processus. Ce n'est pas la perfection qui compte, mais l'amelioration continue et l'adaptation.\"",
    "motivation.quote.author": "- Ma philosophie personnelle",
    "motivation.m1.title": "Proteger les vies numeriques",
    "motivation.m1.desc": "Chaque jour, des millions de personnes dependent de systemes numeriques. Je suis motive par l'opportunite de proteger ces systemes et les personnes qui en dependent.",
    "motivation.m2.title": "Resoudre des problemes complexes",
    "motivation.m2.desc": "La cybersecurite ressemble a un puzzle en evolution permanente. Chaque nouvelle faille ou vecteur d'attaque demande creativite et expertise technique.",
    "motivation.m3.title": "Impact global",
    "motivation.m3.desc": "Les menaces cyber n'ont pas de frontieres. Travailler en cybersecurite, c'est contribuer a la securite numerique mondiale.",
    "motivation.m4.title": "Communaute & mentorat",
    "motivation.m4.desc": "La communaute cybersecurite est collaborative. J'aime partager les connaissances, accompagner les debutants et renforcer les equipes.",
    "motivation.v1.title": "Apprentissage continu",
    "motivation.v1.desc": "La technologie evolue vite, les menaces aussi. Je m'engage a rester a jour sur les outils et techniques modernes.",
    "motivation.v2.title": "Fondation ethique",
    "motivation.v2.desc": "Utiliser mes competences de maniere responsable est essentiel. Je crois en la securite defensive et la divulgation responsable.",
    "motivation.v3.title": "Innovation & automatisation",
    "motivation.v3.desc": "Je cherche a automatiser les processus de securite, creer des outils innovants et gagner en efficacite.",
    "motivation.v4.title": "Partage de connaissances",
    "motivation.v4.desc": "La securite devient plus forte quand la connaissance est partagee. J'aime documenter, enseigner et contribuer.",

    "experience.title": "Stages/Experience",
    "internships.overview": "Apercu",
    "internships.technologies": "Technologies & competences",
    "internships.visitCompany": "Visiter l'entreprise",
    "internships.viewCertificate": "Voir le certificat",

    "activity.eyebrow": "Open Source & Securite",
    "activity.title": "Activite & Realisations",
    "activity.subtitle": "Suivi de mes contributions open source et de mes progres en formation cybersecurite.",
    "activity.tryhackmeProgress": "Progression TryHackMe",

    "github.contributions": "Contributions GitHub",
    "github.contributions.lastYear": "contributions durant la derniere annee",
    "github.rank": "Classement Tunisie",
    "github.calendar.loading": "Chargement des contributions...",
    "github.calendar.error": "Impossible de charger l'activite GitHub",
    "github.calendar.less": "Moins",
    "github.calendar.more": "Plus",
    "github.achievement.title": "Realisations GitHub",
    "github.achievement.subtitle": "Badges obtenus via l'activite GitHub",
    "github.achievement.error": "Erreur lors du chargement des realisations",
    "github.achievement.hint": "Verifiez que le serveur backend est actif (npm run dev).",

    "tryhackme.profile": "Profil TryHackMe",
    "tryhackme.subtitle": "Progression en formation cybersecurite",
    "tryhackme.level": "Niveau",
    "tryhackme.globalRank": "Classement mondial",
    "tryhackme.percentile": "Percentile",
    "tryhackme.roomsCompleted": "Rooms completees",
    "tryhackme.badgesEarned": "Badges obtenus",
    "tryhackme.error": "Erreur lors du chargement des stats TryHackMe",

    "cv.previewTitle": "Apercu du CV",

    "footer.bio": "Etudiant en ingenierie developpant des systemes d'automatisation de securite bases sur les LLM.",
    "footer.backToTop": "Retour en haut",
    "footer.rights": "Tous droits reserves.",
    "footer.builtWith": "Construit avec React, TypeScript & Tailwind CSS",

    "hire.status": "Ouvert aux opportunites",
    "hire.detail": "- Disponible pour stages et collaborations",
    "hire.vcard": "vCard",
    "hire.cta": "Recrutez-moi",

    "blog.title": "Blog & Articles",
    "blog.subtitle": "Write-ups CTF, recherche en securite et tutoriels IA",
    "blog.back": "Retour au Portfolio",
    "blog.readMore": "Lire plus",
    "blog.comingSoon": "Plus d'articles a venir...",
    "blog.heading.left": "Blog",
    "blog.heading.right": "Write-ups",
    "blog.category.ctf": "CTF",
    "blog.category.security": "Securite",
    "blog.category.ai": "IA",
    "blog.category.tutorial": "Tutoriel",

    "achievements.title": "Realisations en un coup d'oeil",
    "achievements.ieeeRoles": "Roles IEEE",
    "achievements.certifications": "Certifications",
    "achievements.projects": "Projets",
    "achievements.internships": "Stages",
    "achievements.volunteering": "Benevolat",
    "achievements.degrees": "Diplomes",

    "volunteering.back": "Retour au Portfolio",
    "volunteering.navTitle": "Benevolat & Leadership",
    "volunteering.title.left": "Benevolat",
    "volunteering.title.right": "Leadership",
    "volunteering.subtitle": "Engagement communautaire, leadership professionnel et implication citoyenne",
    "volunteering.roles": "roles",
    "volunteering.legend.ieee": "IEEE",
    "volunteering.legend.community": "Communaute",
    "volunteering.legend.jci": "JCI",
    "volunteering.legend.association": "Associations",
    "volunteering.badge.leadership": "Leadership",
    "volunteering.badge.officer": "Responsable",
    "volunteering.badge.civic": "Civique",

    "404.title": "ACCES REFUSE",
    "404.subtitle": "La page que vous cherchez n'existe pas ou a ete deplacee.",
    "404.home": "Retour a l'accueil",

    "cv.title": "Curriculum Vitae",
    "cv.english": "Version anglaise",
    "cv.french": "Version francaise",
    "cv.preview": "Apercu",
    "cv.download": "Telecharger",

    "details.noImage": "Aucune image de certificat disponible",
    "details.issued": "Delivre le :",
    "details.description": "Description",
    "details.skillsVerified": "Competences verifiees",
    "details.viewOfficial": "Voir l'attestation officielle",

    "chat.greeting": "Bonjour ! Je suis l'assistant IA de Malek. Je peux vous parler de ses projets, stages, certifications et competences. Que voulez-vous savoir ?",
    "chat.input": "Demandez-moi ses projets, competences...",
    "chat.send": "Envoyer",
    "chat.error": "Desole, une erreur est survenue. Veuillez reessayer.",

    "welcome.title": "Bienvenue",
    "welcome.subtitle": "Comment souhaitez-vous explorer mon portfolio ?",
    "welcome.technical": "Je suis Technique",
    "welcome.technicalDesc": "Portfolio complet avec projets, competences, blog et plus",
    "welcome.recruiter": "Je suis Recruteur",
    "welcome.recruiterDesc": "Resume d'une page optimise pour les decisions de recrutement",
  },
  ar: {
    "nav.about": "نبذة عني",
    "nav.certifications": "الشهادات",
    "nav.projects": "المشاريع",
    "nav.experience": "التدريب/الخبرة",
    "nav.education": "التعليم",
    "nav.skills": "المهارات",
    "nav.motivation": "الدافع",
    "nav.volunteering": "التطوع",
    "nav.blog": "المدونة",
    "toggle.toFrench": "التبديل إلى الفرنسية",
    "toggle.toEnglish": "التبديل إلى الإنجليزية",

    "hero.subtitle": "طالب هندسة حاسوب",
    "hero.greeting": "مرحباً، أنا",
    "hero.bio": "طالب هندسة يبني",
    "hero.bio.highlight": "أنظمة أتمتة أمنية مدعومة بنماذج اللغة الكبيرة",
    "hero.bio.rest": ".",
    "hero.stat1": "تقليل 60% من الاختبارات اليدوية",
    "hero.stat2": "85% كشف OWASP",
    "hero.stat3": "أفضل 5% TryHackMe",
    "hero.bio2": "خبرة قوية في الذكاء الاصطناعي وDevSecOps وهندسة الأمان القائمة على البلوكتشين.",
    "hero.downloadCv": "تحميل السيرة الذاتية",
    "hero.contact": "تواصل معي",
    "hero.skillsMatrix": "مصفوفة المهارات",
    "hero.askAi": "اسأل الذكاء الاصطناعي",
    "hero.activity": "النشاط",
    "hero.chatbot": "مساعد المحفظة الذكي",
    "hero.backToPortfolio": "العودة إلى المحفظة",
    "hero.contactForm": "تواصل معي",
    "hero.contactName": "اسمك",
    "hero.contactEmail": "بريدك الإلكتروني",
    "hero.contactMessage": "رسالتك",
    "hero.contactSend": "إرسال الرسالة",
    "hero.contactSuccess": "تم إرسال الرسالة بنجاح!",
    "hero.contactError": "فشل إرسال الرسالة، يرجى المحاولة مرة أخرى.",
    "hero.stats.projectsCompleted": "مشاريع مكتملة",
    "hero.stats.experience": "التدريب/الخبرة",
    "hero.stats.certifications": "الشهادات",
    "hero.loading.line1": "تهيئة النظام...",
    "hero.loading.line2": "تحميل وحدات الأمان...",
    "hero.loading.line3": "الاتصال بالمحفظة...",
    "hero.loading.line4": "تم منح الوصول.",
    "hero.loading.systemLabel": "نظام المحفظة",

    "skills.title": "المهارات والأدوات",
    "skills.subtitle": "التقنيات والمنهجيات التي أستخدمها للتطوير الآمن والتحليل",
    "skills.label": "المهارات التقنية",
    "skills.category.languages": "اللغات",
    "skills.category.frameworks": "أطر العمل",
    "skills.category.securityTools": "أدوات الأمان",
    "skills.category.devops": "DevOps والأدوات",

    "certifications.title": "الشهادات",
    "certifications.eyebrow": "الاعتمادات المهنية",
    "certifications.subtitle": "شهادات معترف بها دولياً تثبت الخبرة في الأمن السيبراني والذكاء الاصطناعي والسحابة",
    "certifications.tab.all": "الكل",
    "certifications.tab.dev": "تطوير",
    "certifications.tab.ai": "ذكاء اصطناعي",
    "certifications.tab.cybersecurity": "أمن سيبراني",
    "certifications.details": "التفاصيل",
    "certifications.verify": "التحقق",

    "projects.title": "المشاريع",
    "projects.eyebrow": "المحفظة",
    "projects.featured": "المشاريع المميزة",
    "projects.subtitle": "عرض مشاريع وحلول الأمن السيبراني التي طورتها في بيئات واقعية",
    "projects.tab.all": "الكل",
    "projects.tab.cybersecurity": "أمن سيبراني",
    "projects.tab.ai": "ذكاء اصطناعي",
    "projects.tab.dev": "تطوير",
    "projects.source": "عرض الكود المصدري",
    "projects.highlights": "أبرز النقاط:",
    "projects.more": "المزيد (انقر للعرض)",
    "projects.technologies": "التقنيات:",
    "projects.about": "عن المشروع",
    "projects.modal.highlights": "أبرز النقاط",
    "projects.modal.technologies": "التقنيات",

    "education.title": "التعليم",
    "education.eyebrow": "الخلفية الأكاديمية",
    "education.subtitle": "التعلم المستمر والتميز الأكاديمي في الأمن السيبراني وعلوم الحاسوب",
    "education.coursework": "المواد الدراسية الرئيسية:",
    "education.achievements": "الإنجازات:",
    "education.continuing": "التعليم المستمر",

    "motivation.title": "الدافع",
    "motivation.eyebrow": "ما يحركني",
    "motivation.subtitle": "الشغف والمبادئ التي توجه مسيرتي في الأمن السيبراني",
    "motivation.story.title": "رحلتي نحو الأمن السيبراني",
    "motivation.story.p1": "بدأ شغفي بالأمن السيبراني أثناء دراستي لعلوم الحاسوب عندما تعلمت لأول مرة عن هجمات تجاوز المخزن المؤقت. فكرة أن خطأ برمجي بسيط يمكن أن يؤدي إلى اختراق النظام كانت مرعبة ومذهلة في آن واحد.",
    "motivation.story.p2": "قادني هذا الفضول للمشاركة في أول مسابقة CTF، حيث عشت إثارة القرصنة الأخلاقية ومتعة اكتشاف الثغرات وإصلاحها. الطبيعة التعاونية لمجتمع الأمن السيبراني أقنعتني أن هذا هو المجال الذي أنتمي إليه.",
    "motivation.story.p3": "اليوم، كل مشروع أعمل عليه وكل ثغرة أكتشفها يعزز إيماني بأن الأمن السيبراني ليس مجرد مهنة - إنه رسالة لحماية وخدمة العالم الرقمي الذي نعتمد عليه جميعاً.",
    "motivation.section.motivates": "ما يحفزني",
    "motivation.section.values": "القيم الأساسية",
    "motivation.quote": "\"الأمن ليس منتجاً، بل عملية. لا يتعلق الأمر بالكمال، بل بالتحسين المستمر والتكيف مع التحديات الجديدة.\"",
    "motivation.quote.author": "- فلسفتي الشخصية",
    "motivation.m1.title": "حماية الحياة الرقمية",
    "motivation.m1.desc": "كل يوم، يعتمد ملايين الأشخاص على الأنظمة الرقمية. أنا محفز بفرصة حماية هذه الأنظمة والأشخاص الذين يعتمدون عليها.",
    "motivation.m2.title": "حل الألغاز المعقدة",
    "motivation.m2.desc": "الأمن السيبراني يشبه حل لغز متطور باستمرار. كل ثغرة جديدة أو متجه هجوم يتطلب تفكيراً إبداعياً وخبرة تقنية.",
    "motivation.m3.title": "التأثير العالمي",
    "motivation.m3.desc": "التهديدات السيبرانية لا تعرف حدوداً. العمل في الأمن السيبراني يعني المساهمة في السلامة الرقمية العالمية.",
    "motivation.m4.title": "المجتمع والإرشاد",
    "motivation.m4.desc": "مجتمع الأمن السيبراني تعاوني. أنا شغوف بمشاركة المعرفة وتوجيه المبتدئين وبناء فرق أمنية أقوى.",
    "motivation.v1.title": "التعلم المستمر",
    "motivation.v1.desc": "التكنولوجيا تتطور بسرعة، وكذلك التهديدات. ألتزم بالبقاء على اطلاع بأحدث الأدوات والتقنيات.",
    "motivation.v2.title": "الأساس الأخلاقي",
    "motivation.v2.desc": "استخدام مهاراتي بمسؤولية وأخلاقية أمر أساسي. أؤمن بالأمن الدفاعي والإفصاح المسؤول.",
    "motivation.v3.title": "الابتكار والأتمتة",
    "motivation.v3.desc": "أسعى لأتمتة عمليات الأمان وتطوير أدوات مبتكرة وتحسين الكفاءة في العمليات الأمنية.",
    "motivation.v4.title": "مشاركة المعرفة",
    "motivation.v4.desc": "الأمن يصبح أقوى عندما تُشارك المعرفة. أستمتع بالتوثيق والتعليم والمساهمة في المجتمع.",

    "experience.title": "التدريب/الخبرة",
    "internships.overview": "نظرة عامة",
    "internships.technologies": "التقنيات والمهارات",
    "internships.visitCompany": "زيارة الشركة",
    "internships.viewCertificate": "عرض الشهادة",

    "activity.eyebrow": "المصادر المفتوحة والأمان",
    "activity.title": "النشاط والإنجازات",
    "activity.subtitle": "تتبع مساهماتي في المصادر المفتوحة وتقدمي في تدريب الأمن السيبراني.",
    "activity.tryhackmeProgress": "تقدم TryHackMe",

    "github.contributions": "مساهمات GitHub",
    "github.contributions.lastYear": "مساهمة في السنة الماضية",
    "github.rank": "ترتيب تونس",
    "github.calendar.loading": "جاري تحميل المساهمات...",
    "github.calendar.error": "تعذر تحميل نشاط GitHub",
    "github.calendar.less": "أقل",
    "github.calendar.more": "أكثر",
    "github.achievement.title": "إنجازات GitHub",
    "github.achievement.subtitle": "شارات حصلت عليها من نشاط GitHub",
    "github.achievement.error": "خطأ في تحميل الإنجازات",
    "github.achievement.hint": "تأكد من أن الخادم يعمل (npm run dev).",

    "tryhackme.profile": "ملف TryHackMe",
    "tryhackme.subtitle": "تقدم التدريب على الأمن السيبراني",
    "tryhackme.level": "المستوى",
    "tryhackme.globalRank": "الترتيب العالمي",
    "tryhackme.percentile": "النسبة المئوية",
    "tryhackme.roomsCompleted": "الغرف المكتملة",
    "tryhackme.badgesEarned": "الشارات المكتسبة",
    "tryhackme.error": "خطأ في تحميل إحصائيات TryHackMe",

    "cv.previewTitle": "معاينة السيرة الذاتية",

    "footer.bio": "طالب هندسة يبني أنظمة أتمتة أمنية مدعومة بنماذج اللغة الكبيرة.",
    "footer.backToTop": "العودة للأعلى",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.builtWith": "بُني باستخدام React وTypeScript وTailwind CSS",

    "hire.status": "مفتوح للفرص",
    "hire.detail": "- متاح للتدريب والتعاون",
    "hire.vcard": "بطاقة",
    "hire.cta": "وظفني",

    "blog.title": "المدونة والمقالات",
    "blog.subtitle": "تقارير CTF وأبحاث أمنية ودروس في الذكاء الاصطناعي",
    "blog.back": "العودة إلى المحفظة",
    "blog.readMore": "اقرأ المزيد",
    "blog.comingSoon": "المزيد من المقالات قريباً...",
    "blog.heading.left": "المدونة",
    "blog.heading.right": "المقالات",
    "blog.category.ctf": "CTF",
    "blog.category.security": "أمان",
    "blog.category.ai": "ذكاء اصطناعي",
    "blog.category.tutorial": "درس تعليمي",

    "achievements.title": "الإنجازات في لمحة",
    "achievements.ieeeRoles": "أدوار IEEE",
    "achievements.certifications": "الشهادات",
    "achievements.projects": "المشاريع",
    "achievements.internships": "التدريب",
    "achievements.volunteering": "التطوع",
    "achievements.degrees": "الدرجات العلمية",

    "volunteering.back": "العودة إلى المحفظة",
    "volunteering.navTitle": "التطوع والقيادة",
    "volunteering.title.left": "التطوع",
    "volunteering.title.right": "القيادة",
    "volunteering.subtitle": "المشاركة المجتمعية والقيادة المهنية والمشاركة المدنية",
    "volunteering.roles": "أدوار",
    "volunteering.legend.ieee": "IEEE",
    "volunteering.legend.community": "المجتمع",
    "volunteering.legend.jci": "JCI",
    "volunteering.legend.association": "الجمعيات",
    "volunteering.badge.leadership": "قيادة",
    "volunteering.badge.officer": "مسؤول",
    "volunteering.badge.civic": "مدني",

    "404.title": "الوصول مرفوض",
    "404.subtitle": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    "404.home": "العودة إلى الرئيسية",

    "cv.title": "السيرة الذاتية",
    "cv.english": "النسخة الإنجليزية",
    "cv.french": "النسخة الفرنسية",
    "cv.preview": "معاينة",
    "cv.download": "تحميل",

    "details.noImage": "لا توجد صورة للشهادة",
    "details.issued": "صدرت في:",
    "details.description": "الوصف",
    "details.skillsVerified": "المهارات المُتحقق منها",
    "details.viewOfficial": "عرض الاعتماد الرسمي",

    "chat.greeting": "مرحباً! أنا المساعد الذكي لمالك. يمكنني إخبارك عن مشاريعه وتدريباته وشهاداته ومهاراته. ماذا تريد أن تعرف؟",
    "chat.input": "اسأل عن المشاريع، المهارات...",
    "chat.send": "إرسال",
    "chat.error": "عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.",

    "welcome.title": "مرحباً",
    "welcome.subtitle": "كيف تريد استكشاف ملفي الشخصي؟",
    "welcome.technical": "أنا تقني",
    "welcome.technicalDesc": "ملف كامل مع المشاريع والمهارات والمدونة والمزيد",
    "welcome.recruiter": "أنا مسؤول توظيف",
    "welcome.recruiterDesc": "ملخص صفحة واحدة مُحسّن لقرارات التوظيف",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("portfolio-lang");
    if (saved === "fr" || saved === "ar") return saved;
    return "en";
  });

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const handleSetLang = (newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("portfolio-lang", newLang);
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
